USE [SC.Service]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Announcements](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](100) NOT NULL,
	[Summary] [nvarchar](200) NOT NULL,
	[Details] [nvarchar](max) NOT NULL,
	[CreatedOn] [datetime] NOT NULL,
	[CreatedBy] [nvarchar](max) NOT NULL,
	[UpdatedOn] [datetime] NOT NULL,
	[UpdatedBy] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_dbo.Announcements] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET IDENTITY_INSERT [dbo].[Announcements] ON 

GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (1, N'Malini yemesini bilmeyen zengin her gün zügürttür.', N'et enim elementum ornare est libero metus euismod lobortis massa Nam massa at semper elementum tellus odio ut sit Proin sem ut orci vel nisi vel feugiat a accumsan neque', N'velit semper velit est mi viverra elit sit sed tortor nibh mollis risus Aliquam sed vel dolor facilisis risus dignissim diam nec a libero tempor dolor velit ligula sapien diam at Vivamus Nulla sapien non sit ultricies Pellentesque vel mauris lorem sapien tempus ligula ipsum sed at nisl enim dolor vitae sed tempus sit Vestibulum iaculis hendrerit nisi varius facilisis est sed sagittis enim dolor mauris euismod pulvinar risus imperdiet Integer mauris varius gravida aliquam molestie auctor at nunc nisl massa mollis a massa Vivamus eu scelerisque nibh lectus gravida purus eu mattis interdum fringilla nisl vel ligula eleifend Etiam', CAST(0x0000A51A005B2FC0 AS DateTime), N'Duis@Phasellus.lc', CAST(0x0000A3DB001E7CB0 AS DateTime), N'ante@eu.mg')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (3, N'Sopayi yiyen esek, ati geçer.', N'sed ullamcorper mattis Pellentesque consequat amet mollis ut Sed vel purus elit ultricies amet nisl tincidunt Sed ipsum sapien porta a placerat volutpat lectus tempor sed laoreet rhoncus dolor justo', N'leo orci vitae elit eget faucibus Morbi semper risus leo at tincidunt enim vitae tempus pulvinar eget non scelerisque orci venenatis non molestie cursus nisi nunc sapien porttitor vitae in sem interdum leo gravida suscipit mi turpis blandit eu porttitor a ultricies nisl feugiat Quisque velit quam sagittis interdum placerat ut dolor magna porta amet Nullam id mollis eget adipiscing congue ante leo sagittis Etiam enim Pellentesque sollicitudin viverra non pharetra porta metus varius eget Sed in quam Praesent ac auctor In Donec vulputate ante vitae non laoreet Duis mattis lectus posuere tortor condimentum erat in molestie Phasellus et scelerisque', CAST(0x0000A3DC007C6B90 AS DateTime), N'semper@venenatis.tc', CAST(0x0000A2CE00742E30 AS DateTime), N'erat@dapibus.hn')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (4, N'Karniyin doymayacagi yere, açligini bidirme.', N'id quis adipiscing Suspendisse lacinia Sed eu elementum tellus elit in Suspendisse ac id mi volutpat at quam facilisis ante dui leo nisl luctus erat Sed pulvinar nibh scelerisque in', N'vel accumsan laoreet tincidunt quam eget Phasellus ornare id non est elementum rutrum interdum auctor id Praesent nisi metus massa sagittis est ut Vivamus Nullam tincidunt at Duis volutpat bibendum lobortis tincidunt tincidunt sit libero a libero turpis ullamcorper libero diam Duis lobortis turpis mi sollicitudin tristique malesuada semper id sit scelerisque pulvinar leo amet est purus lorem quis dapibus pulvinar imperdiet posuere Integer facilisis eget et augue eget eros dolor tincidunt nec tincidunt nec sed pulvinar facilisis erat quis consectetur Cras auctor nec metus nulla quis quis vehicula auctor dui ullamcorper quam dictum Duis sapien quis egestas ac quis', CAST(0x0000A25D00350250 AS DateTime), N'Vivamus@tempor.mobi', CAST(0x0000A4DF00BDC9F0 AS DateTime), N'ornare@mi.int')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (6, N'Yavuz hirsiz, ev sahibini bastirir.', N'egestas congue mollis odio dolor non elit leo turpis quam metus feugiat est cursus tempor turpis dictum sed a pellentesque gravida Ut at non Proin vel mattis magna diam leo', N'porta sagittis vulputate eget magna eu commodo ut ut ac Aenean placerat Quisque justo nec tincidunt neque Nam diam dictum consectetur nunc sapien elit lacinia Donec vel Ut molestie ante in velit interdum dictum sed Aliquam sapien euismod mauris amet volutpat vel Aliquam at elit purus tortor pharetra elit dolor aliquam condimentum est adipiscing dignissim vitae sapien dolor Suspendisse elit cursus nibh a gravida Phasellus porta a nisl tempus Proin Curabitur Pellentesque nec turpis eros rhoncus dolor at Morbi elementum sit metus Cras id vitae consequat augue semper tempus eget consectetur sit lacus vehicula lectus elit massa In gravida pulvinar', CAST(0x0000A346005870A0 AS DateTime), N'ut@Suspendisse.na', CAST(0x0000A3A2007C6B90 AS DateTime), N'lacinia@enim.cl')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (7, N'Adamini yere bakanindan, suyun agir (sessiz) akanindan kork (sakin).', N'Suspendisse euismod ipsum magna tortor in vestibulum lorem at purus adipiscing at nunc pretium porta et Curabitur orci tincidunt Cras et in semper turpis vel Vivamus neque egestas commodo gravida', N'sit Praesent sit condimentum In porttitor feugiat sed tristique volutpat dapibus amet libero ipsum quis tristique fermentum Donec tellus ligula at Nulla auctor ut est sodales vestibulum nibh rhoncus ipsum tortor lobortis a non erat eget erat auctor urna mi purus eu ut lorem Nullam Sed Mauris tincidunt dui Pellentesque Nullam eleifend ut congue egestas Ut sed nulla mattis condimentum massa rhoncus massa at felis sem eget mauris diam nec blandit rhoncus ac Fusce sagittis Nulla posuere Aenean Pellentesque ultricies eu Aliquam volutpat dignissim eget nec rhoncus sem lacus in eros Ut nisl imperdiet Aenean sapien Donec amet volutpat ante', CAST(0x0000A2C000B054A0 AS DateTime), N'sollicitudin@feugiat.al', CAST(0x0000A33B00262D70 AS DateTime), N'Cras@venenatis.mq')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (8, N'Yigit yarasina yigit katlanir.', N'dolor Sed dolor amet Donec egestas congue a eget varius Integer euismod Donec vitae auctor amet a placerat erat Sed ullamcorper at sit cursus non Fusce cursus Maecenas at feugiat', N'risus semper non lorem at tempus scelerisque lorem vel metus turpis lectus lobortis Morbi lorem ornare vel est diam lobortis odio sodales faucibus tortor hendrerit Mauris feugiat luctus Phasellus nibh fringilla eleifend sem lectus erat dapibus vitae tincidunt ac Nunc sed facilisis nisl Suspendisse fermentum odio In nisl congue Sed nec a ullamcorper ultrices quam vel fermentum nibh tellus nisl laoreet felis nisl eget sem semper nisi at non molestie felis vitae adipiscing sit et magna venenatis vehicula eget nec nisl vel libero nunc id fermentum Fusce ut dignissim Sed sem a eu Vestibulum bibendum sodales semper metus at tempor', CAST(0x0000A423009DA760 AS DateTime), N'ullamcorper@vitae.hk', CAST(0x0000A4E6007FB750 AS DateTime), N'purus@vitae.lt')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (9, N'Ayipsiz yâr (dost) arayan, yârsiz (dostsuz) kalir.', N'risus arcu ullamcorper ligula a ac molestie quam eleifend amet purus massa urna vel felis id Duis consequat sollicitudin Duis metus euismod turpis vitae quis nisl vehicula ipsum sapien ante', N'Integer magna elementum tristique massa enim feugiat amet diam sem metus sem vel porta accumsan massa Vestibulum eget cursus faucibus quis Ut orci ac massa ante sem quis porttitor eu id augue Vivamus semper orci viverra nec placerat viverra aliquam quam lectus mi scelerisque fermentum lectus interdum lobortis vel in rutrum mollis a sodales eget enim dignissim consectetur ante gravida semper rutrum turpis sodales iaculis Nulla pharetra Aenean lorem Nullam ipsum dui metus sapien arcu scelerisque vulputate placerat ut malesuada semper id dui aliquam Curabitur arcu Nunc suscipit iaculis Cras Curabitur sem lectus ultricies ac sapien nisi Donec Donec a', CAST(0x0000A4C3003B5380 AS DateTime), N'Cras@urna.fk', CAST(0x0000A2E900152610 AS DateTime), N'leo@feugiat.ci')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (10, N'Ragbet güzel ile zenginedir.', N'eget quis vulputate Maecenas et et mi congue nunc fermentum at ut id tempor metus sit tortor id neque Integer ante nisl cursus pharetra dolor Suspendisse eget erat elit tortor', N'mattis nec ipsum ante sit leo vel tortor ornare leo lobortis dolor In Sed Sed amet porta porttitor elit et mollis justo tincidunt suscipit non Maecenas porttitor Etiam massa aliquet pretium erat egestas at pharetra Donec erat Etiam vestibulum molestie tortor accumsan Ut lacus nunc lectus mi eget at ante quam tempus non nunc tellus nisl libero mauris congue amet et at nunc In dui ultricies ante consectetur est est at sed lectus Mauris porttitor odio amet nisi at vel odio tempor ac rutrum tincidunt non congue id nibh sem elit pretium consectetur eget aliquam Integer nulla nisl sem arcu', CAST(0x0000A3AA00CF5DF0 AS DateTime), N'tellus@ipsum.gl', CAST(0x0000A4EC009AE840 AS DateTime), N'rutrum@arcu.au')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (11, N'Isigini aksamdan önce yakan, sabah çirasina yag bulamaz.', N'amet molestie quis sapien Integer congue hendrerit orci id tempus mollis suscipit Nunc malesuada at orci quis amet ipsum sollicitudin ultrices tempus et lectus Curabitur Etiam ullamcorper ac eu magna', N'consequat mi eget fringilla Nunc quis non mattis et Mauris vel leo ac elit odio venenatis facilisis lobortis hendrerit ligula sed lorem tincidunt imperdiet sollicitudin tristique porttitor nisi euismod sagittis ante condimentum ac Aenean ac libero felis non odio ac augue lorem non amet felis mi ornare rutrum sed Nam arcu massa id mi ligula ante laoreet rhoncus facilisis elit tincidunt rhoncus at Phasellus odio nec pretium commodo est congue et consequat id cursus ultrices libero purus condimentum id pulvinar Curabitur sed Aenean condimentum non hendrerit ut cursus et commodo venenatis nibh et elit in eu nulla euismod ut libero', CAST(0x0000A2BD001B30F0 AS DateTime), N'vel@orci.sz', CAST(0x0000A4A000754770 AS DateTime), N'rhoncus@at.fm')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (12, N'Bosbogazi cehenneme atmislar, ?odun yas? diye bagirmis.', N'Aenean ultricies quam sed purus tortor nisl nec sem Donec rutrum est eu Ut varius Curabitur viverra volutpat laoreet Aliquam vestibulum tortor placerat dolor tellus libero vitae ut blandit volutpat', N'et tincidunt eleifend Cras velit sit Pellentesque vestibulum metus sagittis gravida dignissim amet aliquet rhoncus facilisis sed id odio sapien imperdiet augue nunc gravida dolor Ut eu ultricies vitae massa mattis non pretium nisl amet velit eu sit nibh est congue ut odio placerat id nisl nibh id ac eu augue rutrum tincidunt dictum sed ornare ante auctor sagittis consequat massa in Sed eget dapibus orci dui bibendum aliquam feugiat iaculis massa sed gravida Aliquam at sit laoreet sagittis dui Curabitur nisi euismod euismod venenatis lobortis in ante Phasellus suscipit Nullam mattis lacinia ornare nunc at elementum gravida mollis nisi', CAST(0x0000A32B008721C0 AS DateTime), N'amet@pharetra.in', CAST(0x0000A2EF0010C110 AS DateTime), N'eget@nec.sz')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (13, N'Varsa pulun,herkes kulun;yoksa pulun,dardir yolun.', N'sed odio dolor nunc posuere sem Ut arcu bibendum vestibulum sem blandit arcu neque Pellentesque nibh Praesent scelerisque eu imperdiet turpis rutrum Ut Sed lobortis felis porta id magna luctus', N'metus Praesent eget consequat sit leo venenatis quis vitae et justo eleifend tincidunt lobortis nec congue iaculis risus Mauris fringilla sit quam sem pharetra elit varius euismod vulputate nunc pretium felis velit imperdiet varius amet placerat dapibus eget ut at lacinia orci neque amet vel ut justo iaculis Vestibulum tortor Vivamus nisi non at in ultricies mi euismod eu vulputate semper Duis adipiscing fermentum massa sed Praesent Cras massa sed dictum non Nulla auctor justo auctor ac Vivamus non hendrerit Etiam pulvinar Aenean arcu tempor mollis Nunc sagittis ornare Morbi at eget congue bibendum dignissim tempus imperdiet lacinia congue Morbi', CAST(0x0000A309002D5190 AS DateTime), N'nunc@vel.mm', CAST(0x0000A45C00CF5DF0 AS DateTime), N'magna@hendrerit.edu')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (15, N'Haddini bilmeyene bildirirler.', N'Pellentesque vestibulum arcu aliquet quam pharetra quis laoreet massa nisi nulla dictum mollis luctus faucibus ut ante Nullam mi sit Praesent malesuada eu magna Integer egestas nunc mollis nibh leo', N'enim placerat Mauris euismod metus mollis lectus dignissim vel Nullam posuere magna id nunc non dignissim ornare ut ante et nulla dolor eros ipsum placerat diam ut eu aliquam ligula massa eu eget nunc dolor euismod augue sed velit Nulla feugiat bibendum sollicitudin feugiat accumsan Proin est Fusce sodales Phasellus ullamcorper in tortor in magna amet sem auctor bibendum tristique eget sodales eget sodales tellus eget ut vel ac fringilla velit dolor tristique Donec et volutpat molestie purus eros laoreet id at metus et commodo a tincidunt condimentum Aenean eu congue nec urna sit mattis et placerat ullamcorper facilisis magna', CAST(0x0000A4190058FD40 AS DateTime), N'ut@sem.in', CAST(0x0000A3F800C46170 AS DateTime), N'est@ac.it')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (16, N'Agrisiz bas mezarda gerek (olur).', N'nibh adipiscing in odio et commodo lacus Ut rutrum id tellus rutrum felis nisi porttitor aliquet a id a sit lacus Fusce ut facilisis ullamcorper pretium euismod suscipit vel volutpat', N'faucibus lacinia vel ut dui Curabitur Aenean id vulputate Proin sit quis malesuada Sed molestie in at Integer Nam quam Duis turpis amet facilisis lectus varius nunc rutrum accumsan ligula erat sem nunc semper hendrerit Curabitur est nibh tincidunt hendrerit vestibulum eget mollis purus amet lacinia aliquam ac vitae lorem luctus sed massa Phasellus id eget non ante sit et placerat mauris sodales semper id commodo laoreet eu eu posuere non vel sed facilisis ipsum commodo Integer nisl non nec ut purus egestas risus ut erat at elit et adipiscing fringilla pretium malesuada urna quis Curabitur a Pellentesque bibendum metus', CAST(0x0000A45800202290 AS DateTime), N'Pellentesque@sem.gd', CAST(0x0000A30A00754770 AS DateTime), N'Curabitur@arcu.af')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (17, N'Hayvanlar koklasa koklasa, insanlar söylese söylese ( konusa konusa) anlasir.', N'Nulla eu iaculis placerat vitae quis eget tempor quam pulvinar Aliquam est dignissim arcu mi sed id convallis ornare vel accumsan rhoncus tempor et sem turpis accumsan Vivamus In porta', N'quis bibendum aliquet Donec Nullam mollis mollis tortor Integer nisi accumsan viverra eros Morbi imperdiet Vestibulum orci lorem mattis Phasellus condimentum orci vestibulum vel iaculis euismod quis pellentesque augue amet libero Nunc enim mollis urna consectetur enim ornare auctor dignissim sem cursus ac aliquet orci lectus luctus fermentum Vestibulum rutrum vitae placerat eleifend pulvinar fermentum vitae odio Vestibulum Sed vitae faucibus nulla dolor dolor leo vitae sagittis dolor Nam felis Praesent Integer Vestibulum Mauris eu metus in Suspendisse vitae magna imperdiet tincidunt massa diam quam neque sapien placerat porttitor nisi lacus ut et eget erat Pellentesque sed Integer at ornare', CAST(0x0000A5130073A190 AS DateTime), N'mauris@Praesent.rs', CAST(0x0000A334001DA9C0 AS DateTime), N'quis@metus.int')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (18, N'Ari, kizdirani sokar.', N'quam facilisis libero est eget amet mollis convallis ante vel suscipit elit eu arcu nibh ultricies quis turpis sapien eget augue vehicula scelerisque laoreet nunc vulputate ut ut eget augue', N'feugiat quis ante nunc at consectetur congue in tincidunt diam sollicitudin ante metus dictum suscipit sit luctus Aliquam nulla vestibulum convallis porttitor posuere placerat est Donec vel sagittis Phasellus rutrum ut risus amet malesuada Quisque sit at est sollicitudin at sed ut egestas congue vitae amet et Donec faucibus ac pulvinar Nullam turpis In Nulla felis ipsum Donec sagittis posuere tristique nulla Phasellus Phasellus nisi at quis Duis mattis Nulla porttitor ac semper a orci fringilla sit tempor purus lectus vitae ut iaculis massa sem ornare placerat egestas Etiam metus condimentum libero nulla Quisque laoreet dui purus feugiat magna elementum', CAST(0x0000A27E0041EB00 AS DateTime), N'odio@libero.zm', CAST(0x0000A30F001A17B0 AS DateTime), N'facilisis@convallis.dm')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (19, N'Bugday basak verince orak pahaya çikar (kiymete biner).', N'turpis vulputate adipiscing arcu eros quis quam vehicula lobortis erat orci Nulla orci mauris magna mauris erat non justo est at dolor tortor semper vehicula amet non feugiat sodales non', N'nec lacinia lacus at elit id gravida neque nibh rutrum ut et bibendum a Nullam sed ut Etiam vel euismod nisi nisl Aliquam metus quis lorem lobortis lobortis lacus purus sed in lacinia massa sagittis Aenean id tortor nibh massa Aliquam Nunc in dui vitae vitae tortor porta tortor euismod sapien in tincidunt fermentum quis mauris eget sit in vel metus bibendum eget et amet vel metus nec id ante eros ac quis arcu magna fermentum sed nisi quis sodales vitae Pellentesque nisl Nunc ultricies sollicitudin ligula Duis ac justo eros tempor Suspendisse ipsum faucibus ultricies sollicitudin nisi et mattis', CAST(0x0000A44B0046DCA0 AS DateTime), N'Sed@condimentum.kw', CAST(0x0000A46F001C9080 AS DateTime), N'quam@faucibus.as')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (20, N'Yurdun otlusundan kutlusu yegdir.', N'non non sem et nunc dui sollicitudin libero orci et sed non dolor ultricies ac amet libero Duis nisi turpis volutpat in Integer vel elementum volutpat iaculis eleifend feugiat ante', N'sagittis Sed dolor varius tellus sed arcu Aliquam Nam vel aliquam felis sem diam ante fermentum sagittis rutrum Aliquam vitae at varius erat vitae tincidunt ligula et sem ac amet nisi sit justo pretium urna tempus ut eget at viverra molestie hendrerit lectus aliquet Cras in vel sed eros lorem Nulla rhoncus ante libero sem Mauris risus Suspendisse amet ante Pellentesque iaculis Donec Nulla Phasellus Etiam sit at sagittis eget sollicitudin semper molestie sem dictum venenatis sem nec justo adipiscing Curabitur bibendum Nulla nunc at rutrum porta nunc tincidunt mattis Fusce Nulla in laoreet ac rhoncus lacinia Fusce volutpat elementum', CAST(0x0000A2F60036A830 AS DateTime), N'molestie@mauris.no', CAST(0x0000A46A0032CFD0 AS DateTime), N'elit@libero.yu')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (23, N'Ne yavuz (azgin) ol asil, ne yavas (saskin, miskin) ol basil.', N'condimentum Maecenas gravida dolor tortor non eros non amet lorem iaculis tempus tincidunt diam enim malesuada purus ut malesuada auctor ornare at non vel et tristique iaculis ullamcorper tortor Nunc', N'hendrerit massa Fusce Aenean lacus accumsan neque tincidunt a velit rutrum fermentum et felis in aliquet Proin semper a at nec lectus Nam dignissim Praesent malesuada scelerisque felis Nullam Phasellus Integer Aliquam venenatis turpis at dapibus vulputate ut eu augue et massa nisi in odio eros gravida tristique eget amet Aenean amet dignissim lectus auctor Proin sodales Vestibulum purus velit aliquam Mauris ipsum metus eget id eget at convallis laoreet eu Etiam lacinia est tincidunt mauris at Mauris placerat ut orci nisl amet a tincidunt felis ipsum dui massa pulvinar tristique non tristique Vivamus tortor rhoncus sed dolor metus a', CAST(0x0000A32800C115B0 AS DateTime), N'sed@sodales.am', CAST(0x0000A50E0049E210 AS DateTime), N'id@Nullam.by')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (24, N'Can bogazdan gelir.', N'lorem eget Aliquam enim velit libero tortor varius Donec volutpat pulvinar Donec Etiam gravida amet lectus quis sem vestibulum luctus Donec turpis dapibus justo erat amet at quis tellus sapien', N'Vivamus convallis Mauris scelerisque scelerisque lectus a Quisque quam at sem laoreet sodales lobortis sem enim metus quis eu orci quis convallis nulla Donec Vivamus feugiat suscipit iaculis elit interdum risus arcu quam est massa ut Nam pulvinar Etiam lorem Etiam libero eu vulputate venenatis aliquet fermentum sapien diam ut id Donec neque metus eget ut Etiam bibendum a non et a Ut at vitae augue viverra sem luctus molestie venenatis leo Duis non malesuada lorem luctus nisi tempus condimentum Duis nisi Sed Aenean Suspendisse non semper dignissim et rutrum scelerisque Nulla at ut dictum lectus vitae orci porta nec', CAST(0x0000A358002D97E0 AS DateTime), N'porta@ut.museum', CAST(0x0000A530002EB120 AS DateTime), N'sit@elit.pro')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (25, N'Atin bahtsizi arabaya düser.', N'lorem in elit placerat sagittis porttitor mollis Aliquam Donec Praesent metus a eget Duis ut Nullam quis molestie eget orci Nunc lacus eu volutpat Quisque bibendum tortor Sed scelerisque egestas', N'mi pulvinar Quisque erat felis eu ante hendrerit sit urna nunc scelerisque Sed vulputate sit commodo erat urna tristique vitae convallis semper eros sem arcu nisi porta eros Phasellus Vestibulum in blandit felis condimentum nec augue neque lorem placerat eros aliquam non id Suspendisse sit nibh Nulla purus Sed lacus auctor arcu risus tellus justo commodo imperdiet odio Curabitur Suspendisse non arcu hendrerit lorem urna eleifend amet ac laoreet leo mollis libero nisl nibh pulvinar nec turpis eu nibh orci pharetra odio lacus pulvinar Ut vitae ac ac eget tincidunt dolor malesuada nulla est a placerat mattis in lobortis scelerisque', CAST(0x0000A33100789330 AS DateTime), N'quam@mauris.bf', CAST(0x0000A39F008B86C0 AS DateTime), N'ultricies@justo.ag')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (27, N'Mart ayi, dert ayi.', N'rhoncus odio lectus velit tellus eu elit neque Sed ut a Morbi volutpat Vivamus Integer laoreet ipsum ligula auctor metus pharetra purus luctus ante tellus fringilla a congue sit feugiat', N'at ac dapibus vel eros eu fermentum aliquet lorem a rhoncus amet gravida tincidunt mauris id et feugiat nisl dolor odio et mattis gravida cursus dignissim quis Sed Sed urna in sapien mi Nam magna molestie est lacus eget orci felis Phasellus ullamcorper ut nibh dui euismod vel ligula lacinia placerat pulvinar a id cursus dolor mattis metus at nisl pulvinar Pellentesque felis nisl ligula Donec scelerisque Sed at sollicitudin pretium mauris lectus urna congue interdum quis sagittis vestibulum bibendum Donec augue tincidunt leo Nullam neque tempus pretium lectus orci arcu cursus Nam felis Aenean malesuada Phasellus Duis rhoncus mauris', CAST(0x0000A3B1007055D0 AS DateTime), N'ut@iaculis.ph', CAST(0x0000A4C300CD71C0 AS DateTime), N'ornare@vitae.ki')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (28, N'Keçinin cani sopa isteyince, çobanin degnegine (sopasina) sürtünür.', N'luctus nulla Cras diam elit lacus et condimentum gravida aliquet Ut at pulvinar at vestibulum leo dui sit erat nec Cras at elit purus pulvinar ornare et metus lectus posuere', N'In a amet at egestas mollis ac condimentum Sed turpis egestas rutrum consectetur mollis sodales euismod odio orci massa gravida Cras tortor sed mollis vulputate a dui porta vestibulum nunc Donec placerat tincidunt Cras diam libero quis blandit mi Phasellus luctus rhoncus sem vestibulum Nulla quis nec felis arcu ac risus convallis sit purus rutrum ac eget sodales convallis Aenean Duis eu diam lectus aliquam tellus at dictum quis et quis ullamcorper vitae velit Nullam in sed Duis ligula eleifend feugiat Praesent tempor nisi sapien amet Ut quis viverra volutpat mauris porttitor mauris mauris mollis in eu non at turpis', CAST(0x0000A27700AB6300 AS DateTime), N'nec@arcu.pl', CAST(0x0000A2DE003CF960 AS DateTime), N'bibendum@vehicula.si')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (30, N'Besle kargayi oysun gözünü.', N'dignissim nisl egestas dignissim at quis In Ut ullamcorper ante ac at vestibulum eget aliquet elit Fusce fermentum vulputate a massa risus non lorem hendrerit massa nec Proin faucibus tristique', N'id at nec Nulla orci sed libero eu aliquam dolor lorem Donec id arcu Sed molestie dui malesuada nulla lectus dolor diam Maecenas ipsum ipsum placerat sed in et tortor Vestibulum dignissim placerat justo massa feugiat ut vestibulum Pellentesque at et Mauris hendrerit nisl amet fermentum leo metus eu dignissim Phasellus libero feugiat Integer non nisl vitae ut velit fringilla et In elit sollicitudin purus tincidunt pharetra tempus suscipit amet dictum venenatis tortor id enim Sed pellentesque faucibus diam laoreet amet interdum facilisis varius nibh Nulla Pellentesque dui tristique eget odio amet sit commodo quis venenatis aliquam porta eget Vestibulum', CAST(0x0000A3A60058B6F0 AS DateTime), N'tortor@ac.lv', CAST(0x0000A3140015B2B0 AS DateTime), N'semper@sed.jo')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (31, N'Açin gözü ekmek teknesindedir (olur).', N'amet feugiat in pulvinar tristique In elit enim nulla ultricies cursus in placerat viverra tincidunt commodo a velit dui risus tortor amet dolor est congue dolor consequat sed vestibulum velit', N'enim eget sapien lacus facilisis accumsan commodo metus pulvinar sodales libero mollis augue ullamcorper justo nulla gravida est neque semper Suspendisse turpis condimentum urna at blandit molestie Sed mi Morbi vel metus Phasellus viverra nisl erat Ut tincidunt Vestibulum purus sagittis eleifend Duis id Phasellus malesuada pulvinar ullamcorper Integer nunc ligula dictum Fusce velit ultrices vel porta a tellus elit fermentum amet urna eu arcu dictum Quisque Sed vitae nunc suscipit ante eu eleifend dignissim Curabitur orci ligula nec Quisque lectus iaculis felis eget nulla Sed Aliquam luctus nisl sed euismod euismod elit risus dolor mollis eu eget vel tellus', CAST(0x0000A44300620D90 AS DateTime), N'at@sed.tw', CAST(0x0000A3D900C90CC0 AS DateTime), N'volutpat@tristique.ke')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (32, N'Besledik büyüttük danayi, simdi tanimaz oldu anayi, babayi.', N'sit condimentum et Nunc mattis laoreet purus metus quam eu a eget nunc sodales molestie sed justo velit ultrices scelerisque arcu mollis vel blandit Pellentesque vehicula Integer sed Cras id', N'sed porttitor pulvinar eget diam risus lorem sit facilisis vitae facilisis cursus augue ante massa elementum varius ultricies eget ac quis diam eget condimentum id mi quis sit ac aliquet tincidunt Phasellus eget Integer tortor mauris nunc fermentum nisi mauris bibendum dolor neque sapien est in ligula aliquet purus Fusce tincidunt id odio diam accumsan ornare mollis eleifend dui augue metus molestie rhoncus cursus congue tortor gravida sem rhoncus a varius justo amet mattis semper tellus vel venenatis commodo Ut nec auctor Aenean ac molestie elit urna tortor in sit tempus eu porttitor erat ut Nullam id eros dictum vel', CAST(0x0000A32900A976D0 AS DateTime), N'nisi@at.gy', CAST(0x0000A4E100C60750 AS DateTime), N'mollis@quis.mc')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (33, N'Büyük balik, küçük baligi yutar.', N'Phasellus Vestibulum ac magna Maecenas ut urna commodo risus id Fusce rhoncus magna Sed nunc quis quis non nulla Nunc vestibulum condimentum a amet sit In in dignissim vel ullamcorper', N'magna ligula est arcu Fusce tincidunt iaculis non erat ipsum Nunc Curabitur placerat Ut Donec mi Phasellus dignissim amet Maecenas neque tincidunt metus metus in congue turpis ligula id nisi dolor Phasellus varius congue tellus tristique aliquet et massa Donec tempor non eu id ut libero vel non placerat leo pretium nec eget imperdiet vestibulum Vivamus erat sollicitudin ultrices Cras Vestibulum nec dui orci cursus interdum est eu vitae Quisque non amet lorem amet neque facilisis euismod condimentum fermentum quam sagittis vulputate laoreet ultrices semper cursus sit eu magna nunc felis Donec erat egestas Ut magna nisl Suspendisse sed quis', CAST(0x0000A4FA0062E080 AS DateTime), N'Mauris@nibh.ki', CAST(0x0000A3F3006180F0 AS DateTime), N'eu@convallis.co')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (35, N'Bugday basak verince orak pahaya çikar (kiymete biner).', N'dapibus quis enim et hendrerit massa vitae Praesent Donec Integer egestas ut ac euismod eget turpis suscipit Praesent odio Donec non quis id non Proin imperdiet luctus mi lacus lacus', N'Proin ac Proin hendrerit nunc tortor purus leo Aenean vulputate posuere eget Pellentesque amet vestibulum risus pulvinar mattis Duis commodo sapien dignissim dignissim Vivamus porta Mauris ut lectus Ut elit dolor mi Morbi egestas ac Curabitur sagittis sed Phasellus felis consectetur viverra suscipit rutrum leo purus eget non convallis et rhoncus Vestibulum mattis ante mollis in libero enim in risus in eu imperdiet Proin ultricies id mi a sem auctor turpis urna faucibus Donec mi mauris Vestibulum commodo Fusce congue mollis dictum Sed dui nisi a pretium at lacinia tortor eget convallis orci lacus et lobortis aliquam orci nunc justo', CAST(0x0000A4E900324330 AS DateTime), N'ut@id.pm', CAST(0x0000A4FE00361B90 AS DateTime), N'augue@enim.so')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (36, N'Isteyenin bir yüzü kara , vermeyenin iki yüzü kara.', N'nec nec tempus sollicitudin ultricies at nulla Proin varius a nisl lorem ut volutpat ante dui luctus dui nec pretium tempus urna gravida sapien eu iaculis tristique sit rhoncus quis', N'vel vitae a vitae nisl volutpat eget lacus volutpat Fusce eros leo Vestibulum eu quam placerat nec ut a hendrerit Proin sollicitudin Donec et condimentum Pellentesque ullamcorper a mauris dolor quis non feugiat iaculis Vivamus venenatis varius laoreet interdum congue quis imperdiet non Sed nec elementum mi convallis ac tellus Nam at non dolor gravida sem ipsum mauris eu suscipit nec interdum euismod felis metus diam Mauris placerat eros facilisis risus condimentum ultricies feugiat feugiat sapien porttitor magna nunc odio eleifend ac quis scelerisque laoreet sit scelerisque gravida purus nunc in adipiscing at Mauris est nisl accumsan cursus at elit', CAST(0x0000A33D00BFFC70 AS DateTime), N'Quisque@posuere.va', CAST(0x0000A51000903210 AS DateTime), N'sed@Phasellus.cat')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (37, N'Beles atin disine (yasina, yularina, dizginine) bakilmaz.', N'libero semper rhoncus facilisis nisl nisl libero purus congue nec viverra Duis in nec ipsum velit Sed congue malesuada ut egestas volutpat augue Fusce tincidunt dictum Nunc porttitor amet nisi', N'quis volutpat vestibulum mauris nulla Praesent vitae a tortor lorem adipiscing sagittis lobortis risus at est libero Praesent semper luctus lacus bibendum odio lectus in Maecenas Nullam nunc malesuada non ullamcorper Integer Phasellus pretium rutrum metus rhoncus cursus mollis lorem amet Pellentesque quis tellus ante eu arcu bibendum nec libero turpis congue varius vitae hendrerit eget malesuada eu vel nisi tempus ac Sed mattis turpis sem leo accumsan Curabitur placerat Ut sem ligula at enim ac Suspendisse laoreet nunc mi tortor dui scelerisque Sed rutrum pulvinar libero ac ullamcorper et in elementum dapibus Sed ut augue Pellentesque Vestibulum pharetra Fusce', CAST(0x0000A25F0092AAE0 AS DateTime), N'ultricies@non.fm', CAST(0x0000A3CD00556B30 AS DateTime), N'vehicula@rutrum.de')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (38, N'Körler sagirlar birbirini agirlar.', N'id aliquam metus et rhoncus mauris pharetra vitae varius Sed feugiat tempor sem id pellentesque bibendum ut Phasellus Ut dictum felis nisi ut ac a eu Vestibulum at amet nisl', N'dolor amet sit sed sapien felis at non suscipit Fusce ante Aliquam Nulla ac sodales Ut placerat dignissim nulla urna amet quam quis non congue nisl sagittis tortor Proin diam ut massa arcu in mi urna odio eu massa suscipit velit Maecenas ut viverra purus vitae magna porta sit vitae orci feugiat euismod eget eget non orci sodales Etiam semper nec sollicitudin libero Donec metus amet tempor congue placerat eu et et Pellentesque metus purus vel felis tortor eu ac eget congue amet mollis amet nisi quis tempus odio sodales id posuere et risus congue placerat hendrerit Quisque suscipit ac', CAST(0x0000A42900361B90 AS DateTime), N'Phasellus@nisi.sm', CAST(0x0000A32F003DCC50 AS DateTime), N'malesuada@mi.nl')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (40, N'Sahin ile deve avlanmaz.', N'eget congue tellus posuere Vestibulum euismod nisl malesuada mattis sem sit accumsan tortor In mollis blandit id eget dolor eget nec amet placerat nec Sed dolor at tristique nisi tortor', N'Phasellus dolor amet feugiat in massa amet Etiam vestibulum vel sodales diam eget erat sapien at sapien commodo et turpis placerat Cras at et eget tempor laoreet massa malesuada non Donec turpis accumsan lorem lorem tempor sollicitudin est non tristique ante ante facilisis et tempor purus malesuada non dictum Sed consectetur a In nibh non at venenatis Ut nisi pulvinar leo non felis sed eu diam metus at vel Donec tellus Vivamus nisi ultricies vel eu lobortis sapien mattis tellus molestie nisl nec amet Aenean a metus tincidunt dapibus dui nulla eu eu turpis semper velit tempus quis nunc euismod', CAST(0x0000A45F005E3530 AS DateTime), N'Duis@sollicitudin.hm', CAST(0x0000A30E00540BA0 AS DateTime), N'placerat@Vivamus.kz')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (41, N'Ates olmayan yerden duman çikmaz.', N'augue scelerisque felis sed sollicitudin tincidunt nec a sollicitudin lacus quis eget libero Cras sed lobortis justo risus enim nec et et ac id venenatis placerat semper facilisis porttitor Praesent', N'pharetra vitae ultricies laoreet mattis sodales arcu et ante cursus ut id dolor velit mi at turpis pulvinar ac ut elit diam vitae et ornare nisi eget erat condimentum hendrerit tincidunt in dignissim Donec ac iaculis arcu viverra et rutrum tincidunt vel Proin faucibus eget placerat molestie quis elit elit quam vulputate pharetra non ultricies ante eleifend lectus massa augue a erat porttitor Morbi In ut tempor ante amet ut sagittis Morbi iaculis vitae risus Phasellus at sed arcu eu accumsan felis elit id interdum hendrerit eros non non nunc lacus nec mauris et fringilla leo consectetur tincidunt dui ipsum', CAST(0x0000A28200A1C610 AS DateTime), N'dictum@vehicula.biz', CAST(0x0000A2DD009988B0 AS DateTime), N'euismod@quam.ec')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (42, N'Ek tohumun hasini, çekme yiyecek yasini.', N'libero dolor mollis vestibulum tempus pellentesque nec quis Curabitur tincidunt sed leo congue fringilla nisl eget ut accumsan leo risus sit mollis urna elit tortor sed augue eget mattis ut', N'massa Quisque sed dolor semper fringilla venenatis auctor ornare commodo Ut et augue sapien interdum amet a eu amet tempus tortor suscipit sagittis interdum facilisis eleifend ac justo tortor mattis imperdiet sodales suscipit Suspendisse tortor odio arcu nisl nisl cursus Nullam lacinia commodo bibendum tellus a id dui Nunc placerat ante at eget placerat at Sed augue sit Maecenas iaculis sed Aenean Quisque gravida Morbi semper velit sodales rhoncus nibh elit Praesent leo vitae ligula varius odio faucibus felis ac euismod enim arcu est tincidunt vestibulum faucibus enim at risus amet ac in Aenean libero Morbi pulvinar nulla ut quis', CAST(0x0000A3240068EB60 AS DateTime), N'fringilla@lorem.uy', CAST(0x0000A36B0016CBF0 AS DateTime), N'pulvinar@tempor.fk')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (43, N'Deveciyle konusan kapiyi yüksek açar.', N'Aliquam eleifend velit dui elementum orci dolor augue nisi blandit id pharetra leo metus Nulla eu mattis purus sodales non Integer vel sit rutrum elit non molestie tincidunt Nam neque', N'eu Morbi sit In velit iaculis vitae id ac semper in ligula diam placerat ac ullamcorper Donec erat metus condimentum Ut purus nec cursus auctor nunc euismod mattis pulvinar porttitor vitae a mollis sem tincidunt et est Mauris purus Maecenas condimentum at diam nisl sagittis at vehicula Phasellus sem Aliquam volutpat adipiscing sem fringilla at molestie feugiat Etiam adipiscing eget ut congue ultricies faucibus amet diam dignissim sodales dictum interdum Pellentesque quis et ut pulvinar Sed accumsan eros pulvinar at in et euismod laoreet Donec pretium cursus in elit semper scelerisque ac mi tempus et id tellus odio pellentesque dictum', CAST(0x0000A4A200864ED0 AS DateTime), N'at@eget.gh', CAST(0x0000A3CC0033A2C0 AS DateTime), N'id@auctor.dj')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (44, N'Akilli düsman, akilsiz dosttan hayirlidir (Deli dostun olacagina akilli düsmanin olsun).', N'est eget ultricies vel tortor pulvinar ipsum mauris id lacus ornare Donec Aliquam mollis Fusce egestas dignissim Nulla magna eget varius mollis Donec Nullam libero dapibus arcu feugiat libero faucibus', N'Donec eget ultricies consectetur Praesent Vivamus lacus bibendum auctor non feugiat ligula malesuada magna ut viverra diam odio Quisque vel quis at eget pulvinar Sed cursus Vivamus sit dui scelerisque at non dolor sollicitudin vel eget molestie in orci vel dolor Ut velit massa arcu pretium eget ante bibendum libero molestie sit non ut a porta Integer arcu aliquet mollis Nullam erat laoreet lacus nunc nisi sodales felis Pellentesque malesuada elit volutpat Sed fringilla eget lorem augue nunc purus tincidunt nibh amet eu Donec consequat at vulputate dictum sed est malesuada adipiscing pretium eget justo vitae euismod enim mollis hendrerit', CAST(0x0000A2A400C34830 AS DateTime), N'quis@turpis.tl', CAST(0x0000A4D60062E080 AS DateTime), N'viverra@dui.il')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (45, N'Dereyi görmeden paçayi sivama.', N'magna leo ultricies bibendum sit lorem ut velit erat tellus ipsum ac ac pulvinar a eget amet pharetra a lectus feugiat nibh dolor felis fringilla Vivamus Nullam Proin sodales purus', N'fringilla imperdiet Proin congue purus placerat malesuada iaculis ut suscipit gravida sit magna erat porta imperdiet faucibus in quis congue lorem blandit justo libero dapibus sem Sed facilisis In pretium sollicitudin tellus sagittis sem amet Aliquam quam magna hendrerit tristique viverra a nisl sem massa congue augue turpis auctor sapien ut a sed nec Duis et lacus nec Mauris eros ante turpis eu sapien nunc Sed turpis in amet elit purus id auctor tortor ultricies at Donec Nunc nec posuere vehicula ipsum a non urna quam convallis sed lorem blandit urna bibendum tincidunt amet sed nunc a leo orci eget', CAST(0x0000A2C30017E530 AS DateTime), N'tempor@nisl.no', CAST(0x0000A4B4009F4D40 AS DateTime), N'ut@aliquet.lr')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (46, N'Tarlanin iyisi suya yakin, daha iyisi eve yakin.', N'aliquet ac neque tristique eget porttitor ut id sed vehicula purus viverra sodales nunc mauris nulla lobortis eros a est varius Vestibulum ut amet Maecenas Duis turpis ac eros vulputate', N'nec sollicitudin dictum Sed condimentum ante mollis lacus at et ipsum arcu Fusce tellus sit et non risus gravida posuere vitae varius id orci Pellentesque Vivamus sodales tristique Pellentesque sem turpis feugiat Duis pulvinar mollis vitae consequat id porttitor nisl ut sodales feugiat magna convallis arcu pellentesque in placerat lacus Nulla sodales iaculis sem Curabitur non Maecenas rhoncus nisi leo sapien sapien nulla sed quis ac nec vitae ante sollicitudin Nunc magna Nullam id arcu bibendum dapibus dapibus purus Quisque porta malesuada eget volutpat id Cras auctor ac Cras sit quam eu vel arcu consequat volutpat facilisis nisi risus laoreet', CAST(0x0000A3DC00B12790 AS DateTime), N'ut@sem.ge', CAST(0x0000A4A200986F70 AS DateTime), N'justo@Maecenas.no')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (47, N'Ecele çare olmaz.', N'scelerisque sit lobortis eget vel odio in Donec suscipit Nunc posuere luctus scelerisque quam semper non gravida et elementum diam eget ut suscipit non nibh justo malesuada sodales Pellentesque in', N'ac id nulla In eros risus hendrerit feugiat dictum dignissim quam ut lacus quam Quisque amet mauris molestie dolor felis convallis ante odio dolor sem ante nulla dolor nunc nibh nec convallis in est Fusce arcu nec volutpat ligula purus orci malesuada quis odio Donec Pellentesque a nunc ullamcorper libero vulputate non Ut mauris turpis justo gravida vehicula metus nec at in sit odio Integer a sagittis varius Nulla amet tempus augue imperdiet elit commodo lorem suscipit in Sed id hendrerit tempor eget consequat porttitor faucibus gravida molestie lectus non leo accumsan nec arcu in Curabitur ligula dui rutrum suscipit', CAST(0x0000A2D000735B40 AS DateTime), N'ante@hendrerit.su', CAST(0x0000A50900145320 AS DateTime), N'congue@nunc.tm')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (48, N'Söhret felakettir.', N'dui interdum quis ornare cursus lacus a Integer est purus Pellentesque feugiat ante nibh elit porttitor accumsan mollis at mauris cursus Ut quis faucibus scelerisque imperdiet nec erat sit Aenean', N'dui in quam Nunc rhoncus in a Nam porta vel accumsan lectus leo ante nec metus egestas eget orci scelerisque viverra lectus nisl dapibus augue pulvinar et libero vestibulum enim eget libero Curabitur tristique eu Vivamus elementum pulvinar venenatis libero ultricies Etiam aliquam at eget sit eget imperdiet blandit iaculis lorem varius amet justo Etiam placerat Suspendisse sagittis ac dignissim ultricies Integer turpis malesuada dictum iaculis eu diam Nunc ultricies ultrices blandit lacinia porta nisi Praesent Nullam lacinia tristique est massa amet turpis facilisis leo diam a eget convallis iaculis gravida ac odio at a Vivamus vulputate diam massa dignissim', CAST(0x0000A41300890DF0 AS DateTime), N'aliquam@Cras.mil', CAST(0x0000A2AA0011DA50 AS DateTime), N'augue@sem.cl')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (51, N'Köpek ekmek veren kapiyi tanir.', N'pharetra non est Nunc nunc turpis sapien molestie convallis bibendum felis vitae eget eu iaculis malesuada nunc consequat dui eu In tincidunt Donec sapien Nam ac eros a pulvinar erat', N'justo condimentum vitae placerat Maecenas venenatis in neque faucibus consectetur velit mauris sit eu tortor porttitor eget vel sem sem placerat mi fringilla Pellentesque ut vel Fusce luctus a lobortis lectus laoreet id sem ac sed bibendum laoreet nisi dictum hendrerit volutpat elit ut tortor odio est ut venenatis Phasellus faucibus Suspendisse sit at elit metus ante convallis placerat felis Cras ipsum suscipit condimentum massa elit dolor nisi sit Phasellus mollis velit euismod pulvinar ut sit in sem Duis a tincidunt rhoncus ultrices ipsum est turpis a nulla Vivamus in sem venenatis dictum vel laoreet volutpat interdum bibendum nisi risus', CAST(0x0000A2CE00175890 AS DateTime), N'turpis@quis.al', CAST(0x0000A373003475B0 AS DateTime), N'varius@Etiam.td')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (52, N'Komsunun tavugu komsuya kaz görünür.', N'accumsan quis a commodo eros sem Sed Donec venenatis et Nunc ut turpis et et scelerisque bibendum non posuere In arcu lobortis id porta eget sodales eleifend quam ante arcu', N'erat dui Donec diam rhoncus mauris Mauris nulla elit nunc mollis ultricies massa sodales scelerisque enim Nulla nisl quam eu Donec Etiam Aenean dui ac lectus blandit Mauris nisl nibh sem mattis pulvinar nec neque augue Aenean gravida imperdiet tellus Aliquam facilisis sapien arcu Donec enim hendrerit nec at mi risus porta enim eu non amet interdum malesuada est orci sit Pellentesque hendrerit bibendum nisl lacus quam libero Cras enim hendrerit et lorem massa quam erat nisl sit convallis nec a nibh at leo molestie lacus nunc vitae in tempor Ut a non tellus et lectus non viverra imperdiet eget', CAST(0x0000A41A002E6AD0 AS DateTime), N'consequat@mollis.au', CAST(0x0000A2F4006A4AF0 AS DateTime), N'libero@massa.so')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (53, N'Harman yel ile, dügün el ile olur.', N'a ut euismod Donec elit sollicitudin ipsum risus magna sit Curabitur quis aliquet quis a amet eget mattis euismod congue sapien erat mauris Donec Fusce placerat sem eros in ultrices', N'cursus arcu Sed Nulla condimentum eget eget hendrerit mattis vestibulum Quisque lectus eleifend velit vitae a non aliquet sed eget Quisque dictum nunc eleifend vehicula Quisque faucibus laoreet sollicitudin Aliquam Donec porta ipsum Aenean et tortor tellus amet eget ligula metus eget arcu elit pulvinar massa amet ligula imperdiet justo ut ante dapibus porta Mauris eu lectus nunc sagittis tortor Fusce augue dapibus dui vitae turpis elit malesuada nisl Duis consectetur non leo vel a velit augue vestibulum libero venenatis vel auctor Cras sed mauris quam fringilla nunc bibendum ac Fusce vel libero molestie pretium vitae mollis et nunc in', CAST(0x0000A2E500377B20 AS DateTime), N'massa@nunc.ps', CAST(0x0000A3C000B61930 AS DateTime), N'sed@ac.bo')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (57, N'Irz insanin kani pahasidir.', N'tortor massa a mattis quam ut hendrerit hendrerit dapibus elit amet sit est Ut semper rhoncus Phasellus enim quis Aliquam felis nisi nec non congue quis id dictum nec rhoncus', N'Nulla Mauris sodales eget orci et elementum dui arcu vel dictum et mollis luctus vel commodo nec purus diam porta tempus aliquet sagittis congue Phasellus at elit orci nec ac Proin Cras malesuada elementum porta gravida tellus adipiscing gravida pretium nec metus neque ut nec sem sit amet id ipsum metus lectus Proin justo malesuada Cras nunc massa Nulla amet Sed dictum Proin ante porta auctor nibh mollis tortor rhoncus et congue justo iaculis facilisis dignissim nec tincidunt Pellentesque Phasellus Donec eleifend est tempus non mi orci Sed facilisis quis massa facilisis erat congue eu mattis vehicula elementum felis aliquet', CAST(0x0000A3E00050BFE0 AS DateTime), N'pellentesque@sit.so', CAST(0x0000A45800914B50 AS DateTime), N'velit@Morbi.il')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (58, N'Büyük balik, küçük baligi yutar.', N'nisl non Curabitur luctus purus amet nec Maecenas leo volutpat porta luctus elementum volutpat cursus amet auctor et vel eget tempus Pellentesque malesuada euismod elit tellus ante quis ac mollis', N'commodo laoreet eget Nulla metus Pellentesque nisl leo urna mauris ac amet hendrerit eros Nullam sem lacinia malesuada sed tincidunt a Cras arcu mi interdum Suspendisse dignissim augue diam augue mollis lacinia dapibus eros neque et erat at in felis tempus ac est ultrices Aenean quis vel lectus ut nisi urna Cras mauris bibendum a suscipit Maecenas eget Maecenas purus purus varius non quis tempor posuere egestas eros Maecenas ut eget est Nulla Aenean eu mollis tellus ut vulputate at interdum laoreet egestas augue convallis Aenean sit non bibendum eros diam Morbi vestibulum at nulla malesuada faucibus fermentum mi tortor', CAST(0x0000A4420013C680 AS DateTime), N'dolor@mauris.fr', CAST(0x0000A34B00728850 AS DateTime), N'lacus@justo.fk')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (59, N'Herkes ne ederse kendine eder.', N'ante fringilla vitae a et cursus nunc feugiat blandit nec hendrerit dignissim enim in non consectetur facilisis nunc faucibus non lectus Duis eu Nunc odio volutpat Praesent auctor mauris amet', N'sollicitudin porta posuere et mauris neque sit sed amet magna iaculis non Aenean dolor mollis velit orci dolor accumsan lobortis leo Phasellus malesuada venenatis erat Aenean sem elit metus interdum sem non Vivamus In Vivamus ut porta ipsum In In sed vitae a Morbi non blandit Suspendisse diam et iaculis ipsum vitae scelerisque Curabitur ut ac pretium malesuada est Phasellus Mauris amet tortor vel Sed tellus mollis orci nisl fringilla quam metus Maecenas a amet tincidunt ullamcorper vitae sem placerat eleifend in tellus ante rutrum ac quis orci eget interdum ante Mauris in dolor sapien posuere nisi neque Aenean mauris', CAST(0x0000A462001266F0 AS DateTime), N'congue@eu.pg', CAST(0x0000A4470081E9D0 AS DateTime), N'augue@arcu.cd')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (63, N'Utanma pazar, dostlugu bozar.', N'sit Nunc auctor et at nisl purus nunc non tellus ut Nunc nisl eget Phasellus a Quisque in enim elit congue purus justo vitae est libero Suspendisse nibh ultricies justo', N'sodales mi ipsum fermentum quis Pellentesque velit at ullamcorper Quisque sit nisl ut elementum dui libero sollicitudin Mauris vel nisi dui Nulla egestas lectus Etiam Nunc ante posuere sit erat nunc congue sem eget ullamcorper Suspendisse dolor nulla euismod sed quis at augue gravida varius dolor Nulla Fusce lobortis sapien orci Pellentesque consectetur purus volutpat dolor dapibus dignissim sollicitudin Aenean non dignissim orci vestibulum lacus in vitae faucibus et nibh justo aliquet Sed nulla id facilisis amet euismod quis at molestie egestas pharetra non turpis mollis et mollis dolor sed nec vitae posuere auctor porta dui nulla vitae In augue', CAST(0x0000A3B7006C3720 AS DateTime), N'cursus@Vestibulum.pg', CAST(0x0000A3010018B820 AS DateTime), N'euismod@sit.lr')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (65, N'El kazani ile as kaynamaz.', N'et ac mattis a ultricies et tortor rhoncus suscipit purus nec euismod condimentum Phasellus libero et dapibus massa nunc eget cursus Donec mollis elit at a aliquet metus sed nibh', N'in non sagittis vehicula Proin varius risus ut in Fusce nulla ut ante vel nec hendrerit id semper ipsum dignissim est imperdiet risus hendrerit tincidunt interdum posuere Proin elementum libero nulla eget ullamcorper odio dictum lorem bibendum pretium nisl posuere dignissim eu metus cursus sed ullamcorper ultricies non tortor In Etiam Nullam interdum nulla Aliquam mollis mi eget Suspendisse elit eget iaculis ultricies purus velit tellus orci tempor diam feugiat ut enim euismod Nulla semper facilisis elit vel condimentum gravida orci Nullam sem id imperdiet libero in massa Ut nisl pretium vulputate Mauris diam ante congue Phasellus dolor gravida ligula', CAST(0x0000A3DC003548A0 AS DateTime), N'at@ut.ru', CAST(0x0000A34500C5C100 AS DateTime), N'bibendum@mollis.ke')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (66, N'Bedava sirke baldan tatlidir.', N'sagittis mollis libero Duis consequat nisl Suspendisse semper auctor a iaculis feugiat imperdiet interdum in euismod ut velit ac nulla leo cursus volutpat vehicula ac id ullamcorper eros tellus quis', N'mattis est dui dui amet non sapien orci Nulla blandit nec quis fermentum nunc ullamcorper ligula elit blandit pretium congue vel Ut ultrices viverra mi sollicitudin nec enim Integer mauris Nunc libero Vivamus tincidunt turpis convallis Ut Maecenas hendrerit lacus augue elit tortor nisi neque rhoncus sodales ac quis porta ut at gravida Aliquam gravida libero sapien odio est nulla Proin risus tincidunt posuere vitae imperdiet tincidunt ipsum rhoncus facilisis sollicitudin Mauris dolor tempus luctus ipsum libero Sed ac ante eu mattis placerat dignissim dapibus erat imperdiet Aliquam nisi sem molestie porta dolor fermentum Praesent cursus dui tortor nulla aliquam', CAST(0x0000A45B006E69A0 AS DateTime), N'vitae@magna.al', CAST(0x0000A3F8004BCE40 AS DateTime), N'sodales@at.ad')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (67, N'Tas yerinde agirdir (Tas düstügü yerde agirdir.)', N'velit metus sed eget ornare non justo dui sodales augue in sapien semper risus hendrerit nisl metus Fusce tincidunt convallis Vestibulum euismod lorem dictum viverra amet imperdiet quis a Nulla', N'scelerisque auctor in massa Nulla justo eget velit ut purus eu velit libero blandit malesuada sit a at vehicula mollis nisi ac sapien Nullam pharetra Curabitur euismod metus Phasellus nec metus Ut adipiscing Mauris id mattis turpis molestie bibendum venenatis rhoncus eros vel vulputate libero ante ut lorem eget sodales placerat rutrum massa tincidunt faucibus molestie orci a erat turpis faucibus eu quis tristique Phasellus Phasellus laoreet at tincidunt hendrerit at nisi convallis massa imperdiet felis eros et mauris libero justo convallis varius Aenean mi dignissim vel Vestibulum nunc mattis quis felis mollis erat augue mi Proin nunc dignissim at', CAST(0x0000A36100CBCBE0 AS DateTime), N'porta@et.gl', CAST(0x0000A2E00011DA50 AS DateTime), N'ipsum@ultricies.lb')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (68, N'Deliye her gün bayram.', N'purus faucibus nibh ac viverra nisi id condimentum ut Nullam nulla egestas tristique varius imperdiet diam vulputate suscipit mollis non nibh hendrerit sed vel velit eu mi quis ante purus', N'aliquam consectetur ac Donec metus malesuada nibh at Pellentesque eu consequat ac et augue nunc vitae Nulla sem Maecenas sit mollis ultricies sed semper ac ligula molestie ullamcorper placerat id non non nisl Duis risus tristique Curabitur orci metus consectetur elementum a a Pellentesque porta Nullam Nullam condimentum ante sed Aenean eu ac nec eros Mauris ante Donec ligula Etiam porta ipsum justo vehicula est eget molestie laoreet nisi In sed eu adipiscing dolor dui amet Nunc nec Duis scelerisque dolor et cursus et tincidunt nibh volutpat dolor Integer in Nullam fringilla Nulla varius dapibus Aliquam a fringilla sapien velit', CAST(0x0000A4D1005B7610 AS DateTime), N'Pellentesque@rutrum.mc', CAST(0x0000A5010052F260 AS DateTime), N'at@quam.yt')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (69, N'Alet isler, el övünür.', N'dolor ac elit pulvinar eget sem consequat eu et Sed et a lobortis a in velit sed Nunc Proin mauris justo sed sed sem amet massa fermentum Integer mauris eu', N'a leo Vivamus ut volutpat Quisque scelerisque purus mauris pulvinar ipsum Integer orci dignissim non scelerisque et sit suscipit neque diam odio venenatis nulla ut neque dapibus eu suscipit semper est porta libero sed ut eget Fusce felis enim porta augue dignissim Sed Nam vestibulum sagittis bibendum id gravida massa scelerisque imperdiet tempor et Nam egestas Morbi felis orci vel turpis massa nibh in vitae risus justo aliquam at nibh dictum sem justo tortor tincidunt cursus felis Curabitur a Ut nisl at convallis consectetur accumsan id vel porttitor vulputate sed condimentum sed ullamcorper a massa neque porta ultricies eleifend Donec', CAST(0x0000A4DA00CA2600 AS DateTime), N'nec@eget.fo', CAST(0x0000A5060019D160 AS DateTime), N'aliquam@non.gy')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (71, N'Iki deliye bir akilli.', N'et et gravida Sed consectetur est In eu Praesent mollis at ut sit sem Aliquam arcu Nulla ut Aenean consectetur tincidunt augue Sed Fusce erat placerat Pellentesque Nullam massa enim', N'vel Sed Suspendisse interdum Mauris nulla tellus malesuada venenatis malesuada amet enim mi Pellentesque scelerisque et erat ac Fusce at sodales vestibulum molestie Cras urna dignissim Nulla dignissim libero enim in neque quis semper imperdiet eget sed nunc ultricies turpis Quisque diam Nulla egestas Maecenas mollis eu lectus urna orci id tellus congue rhoncus elit aliquam at Pellentesque iaculis tempor sit tincidunt auctor non est Phasellus porta eu in in et sit odio Duis elit placerat adipiscing Nulla Proin elementum risus faucibus Ut mollis euismod vel Nunc nec condimentum dignissim Phasellus tellus fermentum et lorem viverra placerat convallis consectetur pharetra', CAST(0x0000A28E0051D920 AS DateTime), N'posuere@ullamcorper.mt', CAST(0x0000A527006EF640 AS DateTime), N'in@at.fj')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (72, N'Vakitsiz öten horozun basini keserler.', N'elit vel in varius mattis Nulla vitae mi diam vel Fusce ut Pellentesque Nam congue quis venenatis at Nulla feugiat Nulla sem Quisque Donec neque quam mollis amet vestibulum velit', N'ultricies in turpis feugiat massa eu in dictum in malesuada feugiat ipsum molestie est metus ac ac at massa sit dapibus quis turpis amet hendrerit et non nisi adipiscing non eget quam Fusce tortor sit nisl et sagittis facilisis metus vehicula ut mi at vel justo justo Aenean varius ac in ipsum luctus molestie dui a tincidunt mattis Proin eget eu auctor ligula laoreet aliquam placerat suscipit vel vitae quis quis mollis nisl sodales sed libero Donec sem diam eget hendrerit egestas tincidunt vel et egestas aliquet vel est Nam id Donec sed tortor odio eu tincidunt elit Phasellus sollicitudin', CAST(0x0000A2C900667290 AS DateTime), N'Donec@non.dm', CAST(0x0000A4D900A6B7B0 AS DateTime), N'Ut@vitae.ec')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (73, N'Çalida gül bitmez, cahile söz yetmez.', N'dignissim bibendum diam leo mollis Donec tincidunt purus nibh lacus nec lectus varius eget eu nec Nulla Curabitur pretium Nulla In ut Nullam vel Suspendisse interdum luctus ullamcorper enim laoreet', N'Aliquam amet leo lorem Curabitur scelerisque Ut Vestibulum id velit egestas vitae tempor eget Sed eleifend dui augue consequat vitae augue Maecenas lorem velit eget odio sapien sem auctor convallis Quisque nulla posuere quam in lectus dignissim amet sapien dui interdum sed tincidunt molestie pulvinar bibendum quis tempus bibendum volutpat tempor Curabitur mi consectetur pulvinar congue convallis justo dignissim purus in In augue molestie fermentum Sed dui libero ac pulvinar ullamcorper porttitor quis Suspendisse Cras in at velit fermentum a et lectus Maecenas semper neque congue elit velit libero sapien ultrices eros pulvinar tempus amet non libero enim varius quam', CAST(0x0000A28D0055B180 AS DateTime), N'diam@congue.tl', CAST(0x0000A3B700933780 AS DateTime), N'eleifend@massa.cn')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (74, N'Aç (arik) at yol almaz, aç (arik) it av almaz.', N'ut Vestibulum euismod sodales eu at at auctor mauris ac id rutrum feugiat lorem consectetur Quisque nunc In eget id non elementum id Proin nunc mauris tempus ac dui Aliquam', N'sed eu tristique sit sit lectus posuere Pellentesque mauris nisi Nullam tempor massa eu felis tempor vitae semper a lacus nunc dolor Aliquam vitae odio lacinia Vivamus sem mattis pulvinar rutrum vitae urna est hendrerit ac sem Proin porta eu Curabitur ac sit consectetur ut mauris Pellentesque sagittis tristique eu Curabitur vulputate sollicitudin metus erat odio luctus justo quis accumsan vehicula lacinia eget felis congue Praesent Donec odio nunc gravida ut massa egestas Phasellus lectus Mauris interdum sit arcu mauris laoreet nisi enim sagittis Phasellus ut et sollicitudin quis Vivamus et ac tortor ac Morbi ante dolor vitae enim vel', CAST(0x0000A48B0028EC90 AS DateTime), N'eu@volutpat.name', CAST(0x0000A3840063B370 AS DateTime), N'gravida@Integer.travel')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (75, N'Kanaat gibi devlet olmaz.', N'nec elit urna justo neque est libero Proin malesuada nibh euismod tortor pulvinar condimentum vitae Etiam mi odio diam Nulla nisi commodo dui dui imperdiet quis ultricies felis erat rhoncus', N'Ut orci elit sed mattis in leo tellus turpis tincidunt urna quis ligula et Cras turpis Donec risus metus eget fringilla lobortis lacus Donec eleifend semper purus ultricies volutpat sit et Integer faucibus eu pharetra vitae convallis pretium In a mattis interdum ac condimentum Sed Vivamus ut mi arcu interdum imperdiet Sed quis dui id pulvinar Donec non id non diam Vivamus Quisque rutrum magna volutpat auctor mattis non placerat nec Donec risus ligula venenatis Mauris eu id eget tincidunt Fusce ante vulputate auctor dolor congue lobortis sed volutpat eu volutpat posuere ut vitae dapibus Sed sed est nunc Curabitur', CAST(0x0000A38700C72090 AS DateTime), N'ultricies@Vivamus.bv', CAST(0x0000A2DB00B240D0 AS DateTime), N'est@tempor.tg')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (76, N'Tarlanin iyisi suya yakin, daha iyisi eve yakin.', N'eget Nunc facilisis Aliquam justo fermentum id Praesent erat porttitor tempus Nunc sodales lorem eros amet tellus non eget suscipit risus in id lacus tortor in aliquam ac ultrices a', N'odio pretium Integer Integer in mattis nibh id nisl lobortis at sapien vehicula aliquet sapien volutpat amet laoreet Cras iaculis ipsum felis vestibulum quis felis Ut Donec urna mauris ultricies in at ipsum at ipsum gravida non ante molestie libero adipiscing turpis nisi sollicitudin porta bibendum hendrerit quis lacus volutpat volutpat Suspendisse metus id laoreet nisi volutpat interdum lacinia lorem massa at Fusce Quisque Morbi id condimentum eget luctus a fermentum justo placerat ac vitae vel pretium pharetra molestie Pellentesque et Cras tortor nisi ut non imperdiet Sed eget nibh porta pretium libero dignissim ultrices Integer fringilla dignissim commodo sed', CAST(0x0000A36F0025E720 AS DateTime), N'quam@at.sh', CAST(0x0000A37200AD08E0 AS DateTime), N'nibh@amet.pe')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (77, N'Bana benden olur, her ne olursa, basim rahat bulur, dilim durursa.', N'quam quis vitae tellus Aliquam pellentesque iaculis nibh nec turpis eros vitae ornare risus sapien ornare ut metus lorem sit tellus id amet Morbi aliquet malesuada erat sodales vitae nunc', N'Ut Phasellus Quisque metus semper Integer posuere sagittis leo mollis suscipit et ante ante porttitor vulputate purus et scelerisque mollis et quis odio mollis ultricies sollicitudin luctus porta quam tempor laoreet amet tincidunt eu magna quis volutpat tempus dui sem lectus amet fringilla facilisis at faucibus eleifend auctor posuere fringilla vel felis in vitae nisl sollicitudin consectetur gravida facilisis porta et dapibus orci dictum varius amet mauris vulputate arcu varius porttitor Fusce pharetra Donec at vitae Pellentesque amet libero justo pharetra gravida ultrices id Morbi ante dolor Nullam eu purus Fusce Donec elit Etiam non adipiscing Quisque Nunc Vestibulum ligula', CAST(0x0000A415002F8410 AS DateTime), N'ipsum@vulputate.ag', CAST(0x0000A45200305700 AS DateTime), N'ligula@dolor.arpa')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (78, N'Gün dogmadan neler dogar.', N'id leo nisl blandit euismod elementum cursus dapibus erat purus lacinia est massa non sem Praesent dapibus mi sit libero placerat fermentum imperdiet et rutrum dolor sagittis justo at eleifend', N'ut a augue metus vehicula malesuada Quisque Aliquam in non metus tortor In Nulla semper congue erat eget vulputate turpis Vivamus dolor Proin Cras metus ut iaculis a augue ipsum odio semper Vestibulum egestas aliquet nisl pretium Etiam dignissim a Suspendisse dictum dui eleifend nec risus a velit Nam mi neque aliquet nisi odio sed purus facilisis interdum Pellentesque lobortis nunc ac orci aliquam eget semper felis justo eget nisl quam nulla leo Sed Suspendisse nec purus aliquet vel Vivamus diam Vivamus at dolor lorem Mauris luctus iaculis faucibus auctor at mauris consectetur velit malesuada bibendum justo tortor vel sollicitudin', CAST(0x0000A367001220A0 AS DateTime), N'sodales@Duis.az', CAST(0x0000A2AF001B7740 AS DateTime), N'ac@sed.mr')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (79, N'Adamin iyisi is basinda belli olur.', N'enim placerat ultrices pulvinar eget Phasellus tincidunt vehicula turpis Nullam vitae amet at nisl at Cras lacus est convallis bibendum sed tincidunt sagittis tellus metus augue elit Mauris a sit', N'pellentesque porta sem orci enim metus nisl dolor id suscipit feugiat sem Pellentesque Integer placerat amet Phasellus Quisque mollis non at nunc diam tempor hendrerit malesuada mi quis sem in felis Ut nec Aliquam Praesent Pellentesque nunc sit id malesuada viverra vitae odio Aliquam ultricies mauris dictum in massa urna nibh malesuada Cras purus a ipsum orci nisi erat ipsum sodales ac Curabitur non Nullam dignissim a Aenean Curabitur a quam dapibus gravida ante turpis dui augue risus leo ipsum ut tortor ut ut metus accumsan non posuere feugiat amet risus enim vel lectus dignissim facilisis pharetra metus at auctor', CAST(0x0000A502001B7740 AS DateTime), N'sem@nisi.pn', CAST(0x0000A37400255A80 AS DateTime), N'at@lacinia.tz')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (80, N'Fazla as, ya karin agritir ya bas.', N'nibh nunc non viverra felis orci Phasellus lobortis venenatis Nam et Mauris laoreet massa diam lectus ligula eget Phasellus leo Vivamus feugiat id eu posuere a ante at lacinia viverra', N'Mauris egestas orci Morbi ultrices pretium Aliquam scelerisque adipiscing quam ac libero eleifend Proin massa justo at vel quam et vulputate sed tortor libero ligula at facilisis porta rutrum aliquam felis Nunc quis Quisque pellentesque non amet iaculis Mauris risus est pulvinar ut sodales purus quam nisl tortor Aenean condimentum gravida amet Nullam imperdiet posuere sit Nullam ipsum id nisl tellus tempus orci tortor massa nunc luctus laoreet mollis a mauris rutrum euismod ligula feugiat dignissim rutrum lobortis sem eget Quisque dolor diam amet nec mi lorem Vestibulum iaculis Mauris malesuada hendrerit mauris luctus leo justo luctus blandit non Sed', CAST(0x0000A43D00C4A7C0 AS DateTime), N'non@luctus.pm', CAST(0x0000A44C007C6B90 AS DateTime), N'lorem@Aenean.ac')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (81, N'Evdeki hesap çarsiya uymaz.', N'tristique molestie at at Phasellus Fusce Nulla eu porttitor mi augue quis in sed tempor massa blandit nec sit odio quis dignissim auctor purus Curabitur erat sed volutpat condimentum ipsum', N'a tortor libero semper Ut augue at pulvinar nec Quisque tellus adipiscing Praesent turpis vitae gravida Aenean sagittis nec non sodales Mauris facilisis lectus Donec Morbi Mauris mauris augue et tempus turpis urna fermentum ipsum quis leo tellus vehicula sapien bibendum consequat pharetra ut non scelerisque augue congue eget ut convallis id tellus elementum elementum Suspendisse lobortis eget sit vitae nunc orci arcu Duis tempor feugiat Curabitur pretium euismod augue id cursus metus Sed et condimentum condimentum justo Nulla leo Aliquam in porta in ante cursus non eget est ut magna elit ligula sem mattis neque non a massa libero', CAST(0x0000A312002EB120 AS DateTime), N'Donec@id.mt', CAST(0x0000A3C5002A4C20 AS DateTime), N'non@aliquam.hn')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (82, N'Çobansiz koyunu kurt kapar.', N'erat odio sed convallis scelerisque sit amet Sed ut nisi tellus ac Donec Nulla volutpat metus Etiam ultricies commodo eu lacus vitae odio ante rutrum Nulla nec Phasellus Praesent nunc', N'nibh Sed varius vitae tortor eget pharetra eleifend nisl egestas orci sollicitudin nunc placerat vel lacinia lorem euismod vulputate et ultricies ac tincidunt Vestibulum at iaculis tempus arcu mauris Vivamus aliquet dictum Duis molestie magna ac nisl in laoreet nunc nisl in ut venenatis nibh libero aliquam eu dignissim nisi Nullam faucibus et dictum sollicitudin ut luctus Vivamus hendrerit tempus metus Sed amet imperdiet ac justo nisl tortor nisl Mauris velit vehicula pharetra sed elementum diam justo eu arcu dolor mollis justo sed Nunc congue sed massa viverra gravida Nunc Cras Praesent erat turpis metus Vestibulum a lorem justo eu', CAST(0x0000A3AF008AFA20 AS DateTime), N'sem@felis.yu', CAST(0x0000A4AC0042BDF0 AS DateTime), N'diam@nulla.int')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (83, N'Zora daglar dayanmaz.', N'Sed consectetur tempor Proin tincidunt metus ultricies dapibus mauris condimentum quam quam Nulla quis dignissim purus dapibus lacinia Donec eget amet sodales eu quis at velit nec mollis auctor nisi', N'volutpat mi massa condimentum Pellentesque nec ipsum ullamcorper Vivamus tortor elit euismod congue quis amet placerat Duis tempor egestas sed quis arcu pulvinar non lectus vestibulum tellus convallis erat feugiat mollis ullamcorper tortor non tincidunt lorem nibh Nullam sodales turpis nec vel Morbi id bibendum aliquet sapien eros eros Nulla aliquam a et nibh purus congue dui quis ante lacus non condimentum tristique urna tempor odio eget elementum Etiam Integer at arcu Suspendisse tortor hendrerit elit bibendum vulputate bibendum sed ante dapibus convallis libero nisi dolor pharetra vel eleifend dictum sodales velit id vitae in In eu velit at ipsum', CAST(0x0000A33A00119400 AS DateTime), N'Morbi@rutrum.cx', CAST(0x0000A534005AE970 AS DateTime), N'eleifend@dapibus.nf')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (84, N'Yalanci kim? Isittigini söyleyen.', N'imperdiet Ut In tellus mattis pulvinar Etiam congue sapien eget varius sollicitudin sed porta metus a pulvinar eget malesuada lectus placerat arcu malesuada eget et diam fringilla Aliquam justo auctor', N'pellentesque eleifend Proin non nulla augue fringilla metus convallis eu elit sodales metus non lacus Phasellus turpis mollis quam ante Nulla molestie Aenean laoreet eleifend sem odio laoreet porta nunc mi sed iaculis placerat sollicitudin eu nisl elit Aenean dui volutpat a lorem id a vestibulum Donec porttitor ultricies vehicula id erat at Nullam quis non sagittis eu at nulla ut sem convallis neque metus augue tellus mi elit ligula lacus urna dapibus sem ipsum dui vehicula in pulvinar rutrum non commodo ultricies ut in ultricies quis dignissim nisi ligula facilisis Nunc purus sagittis porta consectetur eleifend Nunc Nunc imperdiet', CAST(0x0000A37100B89200 AS DateTime), N'pulvinar@id.pr', CAST(0x0000A5040014DFC0 AS DateTime), N'congue@venenatis.id')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (85, N'Irmak kenarina çesme yapilmaz.', N'non Nam ut Proin sit Ut sed a Ut lacinia erat tortor Sed Donec sit nec fermentum vulputate Vivamus ante imperdiet Mauris nisi leo lectus urna in iaculis feugiat sem', N'a ut Nullam posuere Ut porta ante feugiat dictum ultrices Nunc sit semper Nulla posuere augue hendrerit Aenean eget velit orci pellentesque nisl ante mollis porta vestibulum vitae nulla amet Duis Donec bibendum enim nibh hendrerit nec ac lorem nunc porttitor imperdiet mollis iaculis et cursus Vestibulum felis lorem dolor dui in egestas nisi sed Curabitur Morbi imperdiet eget gravida tempor iaculis nunc nisl sollicitudin augue eu tellus nec eget lacinia vulputate erat sodales neque Quisque lacus eros tempus felis dapibus tortor pharetra pretium a augue vulputate lacus sit augue Phasellus tincidunt Quisque sagittis felis gravida ac sit tempor tincidunt', CAST(0x0000A36C00CED150 AS DateTime), N'scelerisque@posuere.tm', CAST(0x0000A48900C08910 AS DateTime), N'justo@risus.va')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (86, N'Bir agaçtan, oklukta çikar boklukta.', N'nisi felis condimentum ante quis rhoncus Phasellus egestas ac amet metus lobortis Nulla sed Nunc Morbi velit id odio turpis et turpis lectus lobortis nisl vel eu et diam blandit', N'euismod orci condimentum tristique In porta velit Vivamus urna rhoncus congue pulvinar mollis Sed sit faucibus nisl diam eget venenatis nisi eget ut consequat quam nisl euismod interdum Sed amet nunc auctor Maecenas tempor nec fringilla non libero id a at condimentum id vehicula a ligula nibh felis vulputate vehicula ut fringilla ultricies fermentum vitae Fusce lorem metus ligula eget nibh Mauris felis amet enim scelerisque non elit arcu ac ante ut tortor nulla at a non porta amet risus Praesent nibh in nibh metus Vivamus sollicitudin pulvinar fringilla libero at urna dui molestie sapien Pellentesque ante In lobortis lorem', CAST(0x0000A29D00CA2600 AS DateTime), N'Nulla@adipiscing.no', CAST(0x0000A4070045C360 AS DateTime), N'id@est.pa')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (89, N'Saçim ak mi kara mi? Önüne düsünce görürsün.', N'ligula mollis ornare ut pulvinar id justo volutpat Vestibulum neque Praesent Maecenas dictum sit Aliquam Cras dolor nec eget volutpat ac augue convallis est pharetra congue dignissim vitae metus ac', N'tortor at non porta justo scelerisque ut ac eu dolor scelerisque erat id vitae neque neque nec arcu nec vitae at In est imperdiet velit ligula a Duis mauris metus nisl at magna dolor lacus quam eu ac dolor ut non Quisque dapibus ligula molestie libero vitae Aliquam metus tristique sodales odio auctor tellus urna dictum In arcu Phasellus sollicitudin orci eget ullamcorper dui in lorem ullamcorper convallis pulvinar augue convallis mauris Aenean ac fringilla tincidunt Sed Nulla tempor at tristique quis eu vitae lectus feugiat quis ac libero sollicitudin Suspendisse nisl vitae velit augue aliquam ultricies purus amet interdum', CAST(0x0000A31B0062E080 AS DateTime), N'velit@tincidunt.ir', CAST(0x0000A430008A6D80 AS DateTime), N'porttitor@tempor.pn')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (91, N'Aç tokun yüzüne bakmakla doymaz.', N'aliquet consectetur at tempor id pretium et nisl Nunc hendrerit in orci dolor orci sed Phasellus enim a vulputate tortor vitae mi enim vestibulum Fusce ornare Nunc ante Quisque dolor', N'sed sit ultricies consequat posuere commodo mattis feugiat eros euismod lacus auctor Nullam posuere placerat Cras volutpat neque mauris Mauris turpis nisi nec venenatis dignissim Donec sollicitudin risus Nunc sem dolor non adipiscing sed hendrerit luctus vitae pretium quis a condimentum sodales eu Integer hendrerit in non vehicula egestas condimentum consectetur vel nunc feugiat accumsan amet tellus tellus vulputate sem quis ac ligula ipsum tellus ultrices sodales at at neque eu sapien lacinia placerat pellentesque elementum nunc urna tellus a nec convallis eu lorem Mauris suscipit ut et nec commodo odio tempus Mauris feugiat Ut mollis tristique dictum mattis elit', CAST(0x0000A4A500A59E70 AS DateTime), N'diam@interdum.zw', CAST(0x0000A4E800BBDDC0 AS DateTime), N'ligula@nec.eg')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (92, N'Böyle gelmis böyle gider.', N'Pellentesque a cursus Vivamus est vitae Sed mollis pulvinar eu eleifend ac in Cras tempus amet vel mauris lectus at fermentum Mauris ac at lectus sodales adipiscing sit Mauris risus', N'enim dapibus elit consectetur nulla tempor ultrices faucibus Pellentesque leo mattis nisl mollis libero et quis Sed facilisis blandit vitae vel tristique pretium ut Fusce euismod malesuada mauris quam risus accumsan Proin elit ut vulputate ornare molestie orci Proin ligula metus gravida consequat Sed massa non mi Morbi arcu Curabitur nibh porttitor suscipit lacus malesuada sed dapibus auctor et at sapien lobortis et vitae augue sapien ipsum ac suscipit at Proin amet euismod nisi non dignissim rhoncus metus Mauris at ut nulla dui Ut vitae ac sem et tincidunt libero molestie amet magna nibh placerat purus diam velit rhoncus vel', CAST(0x0000A3EF00AA9010 AS DateTime), N'ligula@imperdiet.zm', CAST(0x0000A47800499BC0 AS DateTime), N'dui@risus.th')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (94, N'At binenin (is bilenin), kiliç kusananin.', N'erat ac ut Cras nisi elit malesuada et velit metus dictum amet laoreet tellus quis sit quis eget Nunc nec at at egestas Nulla quis non Sed eget malesuada libero', N'et imperdiet In nulla sodales aliquet sed auctor turpis adipiscing commodo sollicitudin risus leo Cras in risus eu tristique sagittis lacus porta non eget eget Nunc mauris et leo faucibus imperdiet ac lobortis quam aliquam iaculis viverra dui facilisis rhoncus Phasellus sem mauris convallis Mauris a viverra accumsan luctus Quisque a at bibendum iaculis diam diam dui tempor bibendum nec pulvinar semper Sed ac tortor velit Fusce id est turpis amet quam Integer quis in augue est urna ipsum risus in adipiscing molestie nec tincidunt nunc Nunc sem eu nunc Nulla Phasellus condimentum Proin nibh odio commodo Pellentesque rhoncus enim', CAST(0x0000A35500B00E50 AS DateTime), N'massa@Sed.pa', CAST(0x0000A44100AD9580 AS DateTime), N'bibendum@ut.info')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (96, N'Dikensiz gül olmaz.', N'Donec imperdiet ante semper a lorem ut et tincidunt eget Vestibulum et Nam nunc arcu felis sodales nulla euismod quis sollicitudin hendrerit Nulla Proin dapibus a turpis id Proin a', N'felis fringilla tortor dignissim ante imperdiet Integer quis adipiscing ultricies odio tortor at Sed sit laoreet Nulla sit mi convallis vestibulum nunc enim eros pretium Donec elit sit ullamcorper facilisis nibh non lobortis faucibus lectus mollis quis nunc velit ligula dapibus diam libero Aenean In Donec sagittis ipsum felis cursus sodales mauris nunc ut bibendum sodales Cras eget Suspendisse tellus massa lectus Morbi diam lectus gravida ut mi Sed feugiat quis ut elit malesuada pulvinar odio vestibulum Fusce feugiat mollis ac semper Sed vulputate elementum blandit ac odio in a eget pretium mauris nulla elit eu rutrum mollis sed Pellentesque', CAST(0x0000A3A900A976D0 AS DateTime), N'gravida@ut.ee', CAST(0x0000A534004E8D60 AS DateTime), N'eu@fringilla.mh')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (97, N'Tabak sevdigi deriyi yerden yere çalar.', N'Quisque lectus at vulputate amet nunc Aliquam Praesent volutpat urna dui adipiscing commodo Cras laoreet molestie eget eu lectus tincidunt massa Nunc eleifend molestie nisi at a commodo enim mattis', N'Vivamus iaculis nec nisi fringilla Nulla fermentum pretium leo turpis at eu semper quam ipsum Nunc suscipit semper Nullam dictum augue dictum fermentum pellentesque ut mollis convallis vel risus a imperdiet a amet Pellentesque ipsum semper adipiscing Aenean bibendum faucibus eget fermentum lorem vel Maecenas fermentum rutrum nec quam lacus vulputate faucibus dolor amet Phasellus eget pharetra malesuada vitae eleifend magna luctus dignissim Morbi Mauris enim turpis mi facilisis condimentum sit turpis auctor amet est id odio metus metus iaculis ornare magna consequat massa Sed vehicula Etiam tortor quam in hendrerit vitae eu eleifend a congue scelerisque Cras lorem accumsan', CAST(0x0000A3C60055F7D0 AS DateTime), N'eget@Phasellus.sr', CAST(0x0000A2F200A48530 AS DateTime), N'tincidunt@Vivamus.zw')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (98, N'Zararin neresinden dönersen kârdir.', N'mollis metus Pellentesque Duis rhoncus quam mattis nunc at condimentum ipsum vulputate id congue risus ultrices purus sed ante vulputate euismod dolor cursus ante eu pulvinar est iaculis ante leo', N'ut Integer facilisis Ut quam metus dolor ut sodales tellus mauris in pulvinar euismod lorem ac viverra aliquet mi libero aliquam vitae a purus mattis sodales pellentesque et lobortis ullamcorper aliquam ac mauris eget sit at ut eget volutpat vulputate feugiat sit a at lobortis Cras Praesent sit Aliquam feugiat eu nibh Fusce lectus interdum gravida rhoncus bibendum molestie pellentesque accumsan cursus vel eros elit id venenatis convallis sem elit Duis est ut Sed eu sodales gravida dolor tempus ornare ac eu dui sit quam amet at justo Integer iaculis pulvinar quis placerat Pellentesque mattis In faucibus Sed nunc Vestibulum', CAST(0x0000A4ED00857BE0 AS DateTime), N'in@nibh.lc', CAST(0x0000A42100540BA0 AS DateTime), N'feugiat@consectetur.ws')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (99, N'Gavurun tembeli kesis, Müslümanin tembeli dervis.', N'purus quam nunc enim quam pulvinar iaculis massa sapien laoreet condimentum eget interdum felis diam amet quis bibendum neque scelerisque sit ligula auctor velit orci Nulla varius turpis eu dignissim', N'Etiam nisi Sed et diam feugiat Proin eleifend Vestibulum mi vestibulum gravida Fusce risus Vivamus in quam porta ullamcorper vestibulum quam elit justo velit condimentum placerat non dolor aliquet gravida bibendum arcu odio vehicula ac porttitor non massa gravida ut Fusce enim sodales Morbi sagittis et elit dictum amet nulla aliquet bibendum placerat amet ligula Cras molestie lectus sem sodales sem at a dui a enim porta sodales enim vulputate ante urna congue cursus lacus Ut amet venenatis mauris ultricies sollicitudin porttitor sem euismod mi rutrum augue tortor tempus ac tempus Sed egestas eu Pellentesque porta porta dolor augue massa', CAST(0x0000A4E20089E0E0 AS DateTime), N'nisi@nibh.lv', CAST(0x0000A3F900B0E140 AS DateTime), N'eu@purus.np')
GO
INSERT [dbo].[Announcements] ([Id], [Title], [Summary], [Details], [CreatedOn], [CreatedBy], [UpdatedOn], [UpdatedBy]) VALUES (100, N'Rüzgar eken Firtina biçer.', N'pharetra pretium eu varius porta placerat tellus quis mollis sagittis mauris bibendum ut augue commodo et mattis arcu nec congue purus tincidunt nisl ut vulputate cursus malesuada magna risus Fusce', N'sollicitudin Cras mauris dolor metus nunc aliquam facilisis ut nisi libero gravida mi semper metus mollis iaculis Nullam Curabitur vitae porta erat Nullam Donec augue nisi tempor Cras libero erat at lectus et non risus Integer rutrum nisi nec volutpat metus luctus interdum accumsan sem eros commodo nunc mattis hendrerit suscipit diam non congue mauris Donec Cras sollicitudin venenatis Pellentesque turpis tellus eu nisi quis Quisque massa tempor at diam vitae malesuada metus Mauris quam pretium tincidunt molestie a facilisis ipsum Proin Etiam amet Sed tempor Nunc euismod ac at nisl scelerisque Fusce sem quis risus enim nisl Sed odio', CAST(0x0000A27500CDB810 AS DateTime), N'sed@malesuada.kz', CAST(0x0000A529004C1490 AS DateTime), N'rhoncus@orci.de')
GO
SET IDENTITY_INSERT [dbo].[Announcements] OFF
